model:
  provider: custom
  base_url: "http://localhost:6655/litellm/v1"
  default: "anthropic--claude-4.6-sonnet"

mcp_servers:
  dart:
    command: /Users/D048098/tools/flutter/bin/dart
    args: ["mcp-server", "--experimental-mcp-server", "--force-roots-fallback"]
    timeout: 60
  maestro:
    command: /Users/D048098/.maestro/bin/maestro
    args: ["mcp"]
    timeout: 60
